apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.appName }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resources:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.targetCpuUtilizationPercentage }}